apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: http-echo-rolebinding
subjects:
- kind: ServiceAccount
  name: http-echo-sa
  namespace: default
roleRef:
  kind: Role
  name: http-echo-role
  apiGroup: rbac.authorization.k8s.io

